// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"example/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/assign-role",
				Handler: AssignRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/login",
				Handler: AdminLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/query",
				Handler: UserQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: UserRegisterHandler(serverCtx),
			},
		},
	)
}
